spring.application.name=api

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/macrotrack_db
spring.datasource.username=macrotrack_user
spring.datasource.password=macrotrack_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=1h

# Server
server.port=8080
